error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1310:16)
    at listenInCluster (net.js:1358:12)
    at Server.listen (net.js:1444:7)
    at Function.listen (/home/user/demoProject/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/home/user/demoProject/src/index.js:34:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:863:32) {"date":"Wed Jul 10 2024 14:02:05 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":"EADDRINUSE","port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[1.08,1.01,0.75],"uptime":59320.83},"process":{"argv":["node","/home/user/demoProject/src/index.js"],"cwd":"/home/user/demoProject","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":593150,"external":2671777,"heapTotal":90624000,"heapUsed":69841416,"rss":144379904},"pid":17861,"uid":1000,"version":"v12.22.9"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1310:16)\n    at listenInCluster (net.js:1358:12)\n    at Server.listen (net.js:1444:7)\n    at Function.listen (/home/user/demoProject/node_modules/express/lib/application.js:635:24)\n    at Object.<anonymous> (/home/user/demoProject/src/index.js:34:5)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)\n    at Module.load (internal/modules/cjs/loader.js:863:32)","timestamp":"2024-07-10T08:32:05.348Z","trace":[{"column":16,"file":"net.js","function":"Server.setupListenHandle [as _listen2]","line":1310,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"net.js","function":"listenInCluster","line":1358,"method":null,"native":false},{"column":7,"file":"net.js","function":"Server.listen","line":1444,"method":"listen","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/express/lib/application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"/home/user/demoProject/src/index.js","function":null,"line":34,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":999,"method":"_compile","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1027,"method":".js","native":false},{"column":7,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":863,"method":"load","native":false}]}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:3306 {"name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":"ECONNREFUSED","fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":"ECONNREFUSED","fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at new ConnectionRefusedError (/home/user/demoProject/node_modules/sequelize/src/errors/connection/connection-refused-error.ts:8:5)\n    at ConnectionManager.connect (/home/user/demoProject/node_modules/sequelize/src/dialects/mysql/connection-manager.js:116:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2024-07-10T08:32:05.370Z"}
error: uncaughtException: Please install pg package manually
Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:18:24)
    at new PostgresDialect (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js:15:30)
    at new Sequelize (/home/user/demoProject/node_modules/sequelize/src/sequelize.js:368:20)
    at Object.<anonymous> (/home/user/demoProject/src/config/database.js:25:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:863:32) {"date":"Wed Jul 10 2024 14:04:30 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[1.45,1.05,0.8],"uptime":59466.06},"process":{"argv":["node","/home/user/demoProject/src/index.js"],"cwd":"/home/user/demoProject","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":951896,"external":2929743,"heapTotal":75915264,"heapUsed":56168176,"rss":125583360},"pid":18086,"uid":1000,"version":"v12.22.9"},"stack":"Error: Please install pg package manually\n    at ConnectionManager._loadDialectModule (/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)\n    at new ConnectionManager (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:18:24)\n    at new PostgresDialect (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js:15:30)\n    at new Sequelize (/home/user/demoProject/node_modules/sequelize/src/sequelize.js:368:20)\n    at Object.<anonymous> (/home/user/demoProject/src/config/database.js:25:19)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)\n    at Module.load (internal/modules/cjs/loader.js:863:32)","timestamp":"2024-07-10T08:34:30.572Z","trace":[{"column":15,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js","function":"new ConnectionManager","line":18,"method":null,"native":false},{"column":30,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js","function":"new PostgresDialect","line":15,"method":null,"native":false},{"column":20,"file":"/home/user/demoProject/node_modules/sequelize/src/sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"/home/user/demoProject/src/config/database.js","function":null,"line":25,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":999,"method":"_compile","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1027,"method":".js","native":false},{"column":7,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":863,"method":"load","native":false}]}
error: uncaughtException: Please install pg package manually
Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)
    at new ConnectionManager (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:18:24)
    at new PostgresDialect (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js:15:30)
    at new Sequelize (/home/user/demoProject/node_modules/sequelize/src/sequelize.js:368:20)
    at Object.<anonymous> (/home/user/demoProject/src/config/database.js:25:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:863:32) {"date":"Wed Jul 10 2024 14:05:51 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[1.04,1,0.8],"uptime":59547.35},"process":{"argv":["node","/home/user/demoProject/src/index.js"],"cwd":"/home/user/demoProject","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":1017102,"external":2994949,"heapTotal":76177408,"heapUsed":57514624,"rss":126672896},"pid":18275,"uid":1000,"version":"v12.22.9"},"stack":"Error: Please install pg package manually\n    at ConnectionManager._loadDialectModule (/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js:81:15)\n    at new ConnectionManager (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:18:24)\n    at new PostgresDialect (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js:15:30)\n    at new Sequelize (/home/user/demoProject/node_modules/sequelize/src/sequelize.js:368:20)\n    at Object.<anonymous> (/home/user/demoProject/src/config/database.js:25:19)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Module._compile (/home/user/demoProject/node_modules/pirates/lib/index.js:117:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Object.newLoader [as .js] (/home/user/demoProject/node_modules/pirates/lib/index.js:121:7)\n    at Module.load (internal/modules/cjs/loader.js:863:32)","timestamp":"2024-07-10T08:35:51.867Z","trace":[{"column":15,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/abstract/connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js","function":"new ConnectionManager","line":18,"method":null,"native":false},{"column":30,"file":"/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/index.js","function":"new PostgresDialect","line":15,"method":null,"native":false},{"column":20,"file":"/home/user/demoProject/node_modules/sequelize/src/sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"/home/user/demoProject/src/config/database.js","function":null,"line":25,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":999,"method":"_compile","native":false},{"column":24,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":1027,"method":".js","native":false},{"column":7,"file":"/home/user/demoProject/node_modules/pirates/lib/index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":863,"method":"load","native":false}]}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:38:13.420Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:40:12.879Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:44:11.185Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:48:16.525Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:48:27.587Z"}
error: Could not connect to the database. password authentication failed for user "user" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"323","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:51:23.270Z"}
error: Could not connect to the database. database "exppost" does not exist {"name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":93,"line":"1019","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":93,"line":"1019","name":"error","routine":"InitPostgres","severity":"FATAL"},"stack":"SequelizeConnectionError: database \"exppost\" does not exist\n    at new BaseError (/home/user/demoProject/node_modules/sequelize/src/errors/base-error.ts:26:5)\n    at new ConnectionError (/home/user/demoProject/node_modules/sequelize/src/errors/connection-error.ts:12:5)\n    at Client._connectionCallback (/home/user/demoProject/node_modules/sequelize/src/dialects/postgres/connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (/home/user/demoProject/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/home/user/demoProject/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (events.js:314:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /home/user/demoProject/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/home/user/demoProject/node_modules/pg-protocol/src/parser.ts:104:9)\n    at Socket.<anonymous> (/home/user/demoProject/node_modules/pg-protocol/src/index.ts:7:48)","timestamp":"2024-07-10T08:56:32.066Z"}
